---
openapi: 3.0.0
info:
  title: CourseManager
  description: This API manages all the courses available.
  license:
    name: GNU GPLv3
    url: https://www.gnu.org/licenses/gpl.txt
  version: 1.0.0
paths:
  /courses:
    get:
      responses:
        200:
          content:
            list<Course>:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
  /courses/{course}:
    get:
      responses:
        200:
          content:
            Course:
              schema:
                $ref: '#/components/schemas/Course'
        404: {}
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
    delete:
      responses:
        204: {}
    parameters:
    - name: course
      in: path
      required: true
components:
  schemas:
    Course:
      required:
      - name
      - url
      - id
      properties:
        name:
          type: string
        id:
          type: string
        url:
          type: string
