---
openapi: 3.0.0
info:
  title: CourseService
  description: The API provides content for the course pages.
  license:
    name: GNU GPLv3
    url: https://www.gnu.org/licenses/gpl.txt
  version: 1.0.0
paths:
  /:
    get:
      responses:
        200:
          description: Returns CourseInfo.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseInfo'
  /tasks:
    get:
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskGroup'
components:
  schemas:
    CourseInfo:
      required:
      - description
      - title
      - image
      properties:
        title:
          type: string
        description:
          type: string
        image:
          format: binary
          description: Image URL or data URI
          type: string
    TaskInfo:
      required:
      - title
      - body
      properties:
        title:
          type: string
        body:
          type: string
        media:
          type: array
          items:
            type: string
    TaskGroup:
      required:
      - title
      - tasks
      properties:
        title:
          type: string
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/TaskInfo'
